assembler: main.c compile_and_write_output.c error.c first_scan.c pre_compiled.c global_functions.c second_scan.c symbols.c
	gcc -o assembler -g -Wall -ansi main.c compile_and_write_output.c error.c first_scan.c pre_compiled.c global_functions.c second_scan.c symbols.c  -I.
